### ISSUE TITLE
Header for PR comments unusually large

### ISSUE THREAD

**Issue by dakrone** [mdo/github-wide#18]
Here's a screenshot of a huge header after adding a comment:

![screen shot 2015-03-26 at 12 48 29 pm](https://cloud.githubusercontent.com/assets/19060/6854365/734532d6-d3b6-11e4-85ed-cbc4ac5edb85.png)

Also, every time I try to click a button, the header grows larger and larger.

**Comment by cfoellmann** [comment]
I have the same issue (sometimes) but I was sure it was because of some greasemonkey scripts I run for github.com, too. (Win8.1; FF 36)
I will keep this in mind and test some more.
Anyone else having this issue?

**Comment by pmdarrow** [comment]
I'm having this issue on Chrome with no other user scripts running.

**Comment by mdo** [comment]
Likely some kind of clearfix inadvertently being triggered.

**Comment by auscompgeek** [comment]
```css
.file-header::after {
  clear: left !important;
}
```
seems to fix it.

**Comment by dakrone** [comment]
@auscompgeek that seems to fix it for me too. Thanks!

**Comment by cfoellmann** [comment]
this seems to work for me, too.
See: https://github.com/cfoellmann/github-wide/blob/fix-PR-file-header-bug/github-wide.css for testing purposes. I will run with it some time and will send a PR if no one is faster :grin:
