### ISSUE TITLE
Conversation tab layout is broken in Safari

### ISSUE THREAD

**Issue by leszekgruchala** [mdo/github-wide#24]
Please see attached image. I am using Stylish.

<img width="1398" alt="screen shot 2015-08-18 at 12 32 20" src="https://cloud.githubusercontent.com/assets/89165/9328021/48594d12-45a5-11e5-96bd-fb4b3c2cf77c.png">

**Comment by mdo** [comment]
Should be fine now I think. Looks good to me at least in Safari 9. <3

**Comment by leszekgruchala** [comment]
Thank you!
