### ISSUE TITLE
broken compatibility with github-wide

### ISSUE THREAD

**Issue by artynet** [mdo/github-wide#28]
It seems that github has changed again its CSS so the code is not properly streched out. Just only the top part is affected.
    
Regards, Arturo

**Comment by cfoellmann** [comment]
Can you post some screenshots, please?

**Comment by artynet** [comment]
that's what I meant : 

![github-wide](https://cloud.githubusercontent.com/assets/175003/9568096/a507fff0-4f40-11e5-9615-bddcfbe2de91.png)

the strech is properly made only above the red line. Regards again.

**Comment by singhkay** [comment]
Seeing the same thing as above

**Comment by mdo** [comment]
Oh yeah, myself and another guy ripped out a bunch of layout-specific markup, so this is likely all fucky.

**Comment by mdo** [comment]
Fixed! b6151eb0dce3a2e051a4c77857a8d22ec5f6af4c
