### ISSUE TITLE
Request/Help: Limit to diff view only

### ISSUE THREAD

**Issue by davidhesselbom** [mdo/github-wide#29]
Hello, and thank you for this wonderful tool! It's great for diff views, but I'd like to limit it to be active only in the diff view, and not on other pages on github. Is there an easy way?

**Comment by mdo** [comment]
Use split diffs :). https://github.com/blog/1884-introducing-split-diffs

**Comment by davidhesselbom** [comment]
Split diff makes the page wider, yes, but each column is still limited to half the screen size or so. When you use this tool with the unified view, you get nearly the whole screen width. Anyway, I take your reply as a "no" or possibly "yes but I'm not in the mood" :P Thanks for the reply.

**Comment by mdo** [comment]
Oh, yeah, that's not too difficult to do—I should've asked about unified vs split. There's no real way to do that without something more than CSS since these styles don't have any page classes to hook onto when in unified diff mode. Some fancy JS might be able to solve it, but that's out of my realm of possibilities. Sorry!

**Comment by davidhesselbom** [comment]
Sure, I understand. I'll just use Stylish to manually turn on/off the wide view as required. Thanks!

**Comment by mdo** [comment]
<3

**Comment by cfoellmann** [comment]
you can modifiy
`@-moz-document domain("github.com") {` to limit usage to the specific pages

**Comment by davidhesselbom** [comment]
I'm no CSS guy, so, could you explain roughly how? Do I use regexp in the domain string?

**Comment by cfoellmann** [comment]
info about that you can find here https://github.com/JasonBarnabe/stylish/wiki/Applying-styles-to-specific-sites

**Comment by davidhesselbom** [comment]
Ah, got it! Thank ye kindly :)
