### ISSUE TITLE
Header still has min-width

### ISSUE THREAD

**Issue by ezyang** [mdo/github-wide#32]
![github-wide](https://cloud.githubusercontent.com/assets/13564/11730539/a3b37954-9f4a-11e5-8471-bcd8abe94d3b.png)

github-wide works like a charm for main content, but the header bars still have a min-width applied to them (the screenshot above is for a viewport which is slightly smaller than 980px). Would be great if those would be responsive for smaller widths too.

**Comment by mdo** [comment]
The goal isn't exactly to make GitHub responsive downward on resolution, but upward for larger screens. Unsure I want to tweak that min-width (since I'm also the one that added it to the GitHub header :D) given the nav would need reworking, too.
