### ISSUE TITLE
Section called "Your repositories" runs over the footer

### ISSUE THREAD

**Issue by SergAtGitHub** [mdo/github-wide#36]
Hi @mdo , here is a screenshot of the issue:

![image](https://cloud.githubusercontent.com/assets/5488829/18815548/fd18c9b8-833d-11e6-992b-ac018c803723.png)

You can reproduce this issue by navigating to the github.com and scrolling down to the footer.

**Comment by cfoellmann** [comment]
I am sorry this was more or less ignored but this is old and `v2` should be considered current.
Close !?

**Comment by SergAtGitHub** [comment]
Thanks. Yes, please, close it.

ср, 13 февр. 2019 г., 23:51 Christian Foellmann <notifications@github.com>:
