### ISSUE TITLE
While viewing a long Gist, the horizontal scrollbar is way down at the bottom of the content.

### ISSUE THREAD

**Issue by djangofan** [mdo/github-wide#39]
While viewing a long Gist, the horizontal scrollbar is way down at the bottom of the content.

This is mostly only a problem in cases where content is wider than viewport.  Scrolling to the right to see the un-wrapped content is easier with the scrollbar.  I find myself sometimes scrolling to the bottom of the page just so I can scroll right, and then all the way back up to see the content that didn't wrap.

Maybe this is not something you can change with a theme, and thats ok if that is true.

**Comment by mdo** [comment]
Not really anything I could change, sorry. That's browser behavior.
