### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by mdo** [mdo/github-wide#48]
I made this so many years ago—GitHub's UI has changed drastically. Our nav, header, and more is completely new in contrast. Any thoughts on me carving out a fresh release here, and then changing this repo entirely for a sleeker, full-width-ish CSS variables powered stylesheet?

<img width="1442" alt="screen shot 2018-07-19 at 9 31 49 am" src="https://user-images.githubusercontent.com/98681/42949086-9996f9d4-8b36-11e8-9300-e63f4bd401c3.png">

**Comment by cfoellmann** [comment]
I am pretty happy with the current but if you want to put in the time I am all for it 😀

**Comment by mdo** [comment]
See also #49 to clean this all up. Your flurry or comments inspired me in this hotel lobby this morning :).

**Comment by manicminer** [comment]
An updated version would be great! I just tried out the new dashboard beta and results are suboptimal (to be expected).

**Comment by manicminer** [comment]
_or_... maybe you could lobby for a wide style to be officially adopted? :)

**Comment by mdo** [comment]
@manicminer What's suboptimal about the new dashboard beta?

**Comment by deadman96385** [comment]
Stuff is is off the screen
![photo_2018-07-30_01-45-34](https://user-images.githubusercontent.com/2042793/43381572-ad9f4028-939a-11e8-9737-fb1b7611f097.jpg)

**Comment by mdo** [comment]
@deadman96385 I should have clarified, but the screenshot helps. It's off the screen because of this stylesheet, not the initial changes.

**Comment by manicminer** [comment]
Sorry my comment wasn't clear. That is what I meant - the stylesheet doesn't play so nice with the new dashboard. Though I prefer the rest of the site being wide to having a working dashboard page :D

**Comment by marcoesposito1988** [comment]
This seems to be caused by the .dashboard-sidebar class. Commenting out line 73 in github-wide.css solved the problem for me (this is easily done with the edit function of Stylus for Firefox).
