### ISSUE TITLE
any way to enlarge the network graph

### ISSUE THREAD

**Issue by cfoellmann** [mdo/github-wide#50]
is there a way to enlarge the network graph?
![2018-07-19 1](https://user-images.githubusercontent.com/1256090/42951486-8d7acc12-8b76-11e8-9c84-637fab91606c.png)

That would be a big plus for readability

**Comment by mdo** [comment]
Not sure! I never look at the network graph these days anyway—I've no idea how it's built even working at GitHub haha.

**Comment by cfoellmann** [comment]
in v2: can you limit the box containing the graph? So it won't have this ugly effect.

**Comment by mdo** [comment]
#49 will fix it with a `max-width`, but no plans to dig into the JS to fix the rendering beyond that.
