### ISSUE TITLE
Which extension causes privacy concerns?

### ISSUE THREAD

**Issue by dpo** [mdo/github-wide#53]
The README says
```
#### Stylus
Website: [Stylish](http://add0n.com/stylus.html)

#### Stylish
> Due to privacy concerns (extension has permission to all your browser data) Stylus is recommended.

Website: [userstyles.org](http://userstyles.org)
```
I find the above confusing. Under the "Stylus" header is a website named Stylish (with an address containing "stylus"), while under the "Stylish" header, Stylus is recommended, and the website has a name that is neither "stylus" nor "stylish".

Which one is recommended in the end?

**Comment by PoorPocketsMcNewHold** [comment]
Stylus is recommended. [https://arstechnica.com/information-technology/2018/07/stylish-extension-with-2m-downloads-banished-for-tracking-every-site-visit/](https://arstechnica.com/information-technology/2018/07/stylish-extension-with-2m-downloads-banished-for-tracking-every-site-visit/)

**Comment by cfoellmann** [comment]
There is definitively a problem with the wording.
I will make it clearer and add the reference mentioned by @PoorPocketsMcNewHold . 
PR is coming

**Comment by dpo** [comment]
Thank you.
