### ISSUE TITLE
Pull request comments not full width in Files tab

### ISSUE THREAD

**Issue by jglick** [mdo/github-wide#54]
Compare https://github.com/jenkinsci/workflow-job-plugin/pull/104#discussion_r213702802 to https://github.com/jenkinsci/workflow-job-plugin/pull/104/files#r213702802: the former is full-width, the latter is not.

**Comment by mdo** [comment]
I think this is all set now!

**Comment by jduan-highnote** [comment]
@mdo first of all, this CSS style is amazing and indispensable to me! Thank you for providing it for free.

I still see this problem. Please see the screenshot. When I view comments on the "diff page", they are not as wide.

<img width="2202" alt="SCR-20240918-hgoq" src="https://github.com/user-attachments/assets/a7c6046c-620b-4824-8c44-2707d901918a">
