### ISSUE TITLE
Why isn't this the default for GitHub.com?

### ISSUE THREAD

**Issue by fr0** [mdo/github-wide#55]
You said in the Readme that you work at GitHub...
I know it's non-zero work to "ship" this as the default, but it seem worth it. Please do this. All users would benefit.

**Comment by mdo** [comment]
It's a decent first step, but it would require a lot more work. As it stands now, there'd at least be some significant problems to readability with long line lengths and that kinda stuff. I don't feel strongly about full-width styles though—I appreciate that the right pages are full-width when it'd benefit me most.

All that said, not up to me anymore to ship this :). The priority for the team is to make everything responsive (so we can remove our duplicative mobile-only views) and have more features on mobile devices (plus better split screen support!).

Also, I'd really rather have dark mode before any of that lol.
