### ISSUE TITLE
Fix for homepage

### ISSUE THREAD

**Issue by marcoesposito1988** [mdo/github-wide#56]
First of all: thanks a lot for this style, it is a nerve-saver!

I have noticed however, that it currently scrambles my homepage (see the attached screenshot below).

<img width="1440" alt="bildschirmfoto 2019-01-12 um 13 44 42" src="https://user-images.githubusercontent.com/439893/51073396-9694e780-1670-11e9-975b-3369d0f7384b.png">

I was able to fix the problem by just commenting out the .news and .dashboard-sidebar classes from github.css. I can make a pull request if you'd like, but first I wanted to ask:

- do you foresee any problem in any other page than the homepage? I haven't found any yet
- should the pull request be against master or the v2 branch?

**Comment by cfoellmann** [comment]
please send your PR going for `v2` ASAP!!
Would be greatly appreciated. I will update the userstyle soon

**Comment by mdo** [comment]
Sorry haven't been paying tons of attention here—happy to review a PR to make some quick fixes here!

**Comment by cfoellmann** [comment]
@mdo how about merging `v2` into `master`?

**Comment by raerae1616** [comment]
Yep this affects me also... looking forward to a fix.
