### ISSUE TITLE
why do you have a light header

### ISSUE THREAD

**Issue by cup** [mdo/github-wide#57]
i see here that you are sporting a light header:

https://github.com/mdo/github-wide

however the default header is dark - if im not mistaken it was you yourself that
deployed the dark header:

https://twitter.com/mdo/status/830138373230653440

and now you are not using it?

**Comment by mdo** [comment]
It's also an old repo layout (and I deployed the current one of that, too). The screenshot is from four years ago. Little to nothing is accurate there other than it being wide.
