### ISSUE TITLE
Consider hosting on GitHub.

### ISSUE THREAD

**Issue by Grossdm** [mdo/github-wide#64]
As an alternative to userstyles.org, have you considered just hosting the style here on GitHub?

Thank you.

**Comment by cfoellmann** [comment]
You can easily copy and paste the style from here!

Is there a way to Provide a version that can be automatically picked up by a browser extension?

**Comment by PrincessRTFM** [comment]
I believe Stylus (the improved, non-tracking Stylish) treats `.user.css` files the way Greasemonkey/Tampermonkey does, so a raw link to it should work for that.

**Comment by mdo** [comment]
Comments here I think addressed this enough :).
