### ISSUE TITLE
Last commit 17c1ba0 broke GHE PR Conversation tab

### ISSUE THREAD

**Issue by LunaticoCR** [mdo/github-wide#68]
After the latest commit [17c1ba0](https://github.com/mdo/github-wide/commit/17c1ba0d2cb37cf85e4f1ad477e4ae1a73e58b13) the Conversation tab full width got broken, instead of showing full width it shows a narrow conversation and aligns it to the left.

![image](https://user-images.githubusercontent.com/2124383/62862574-1d409e80-bcfe-11e9-9d0c-409f38096952.png)

**Comment by cfoellmann** [comment]
I can not reproduce this. :-(

**Comment by LunaticoCR** [comment]
It must be something to do with my GHE version...
```GitHub Enterprise Server 2.16.4```

**Comment by cfoellmann** [comment]
sorry. Didnt realize the GHE. I am only a github.com user

**Comment by mdo** [comment]
Ah, GHE doesn’t have the latest code from Dotcom, so you’ll wanna use the older releases there.

**Comment by LunaticoCR** [comment]
Yes that's what I'm doing, thanks!
