### ISSUE TITLE
Github Enterprise Support?

### ISSUE THREAD

**Issue by JohnAJimenez** [mdo/github-wide#72]
Every time there is an update update to the style, I need to manually enter in any of the enterprise github urls I use.
I came up with the following regex that appears to work for both public & GHE and wanted to see if anyone else felt it would be of value.
Instead of matching just for the github.com domain, you can match against the regex expression `https?://github\..*`
this would match the standard github.com but also the github.enterprise-domain-here.com domains.

**Comment by mdo** [comment]
This could make sense to put into the readme perhaps?

**Comment by pthariensflame** [comment]
Note that not all GitHub Enterprise deployments fit that model: the one I'm most often using is of the form `https://github-dev.[REDACTED]`.

**Comment by mdo** [comment]
Closing as a won't fix unless there's something folks want to add as general enough guidance in the readme. Thanks!
