### ISSUE TITLE
Individual issue text boxes in GitHub Enterprise Server 2.18.10 to not flow to width of window.

### ISSUE THREAD

**Issue by garfi303** [mdo/github-wide#73]
The CSS file github-wide.css  makes my list of issues automatically resize to the width of the browser, but not the text fields in each issue. That's a problem for me, because our issues tend to have source-code in them that is too wide for the window. I was hoping that this would allow the windows to expand horizontally when I made the browser window wider.

Don't get me wrong --- this is a great CSS package --- but it would be more useful for me if it made more of the layouts responsive.

**Comment by mdo** [comment]
You're welcome to expand the widths there, but I've kept them narrower on account of readability with line length. Lines of text that are too wide become difficult to track and parse.

**Comment by simsong** [comment]
I don’t want the widths to be fixed, I want them to flow. Is there an  easy way to do that?

**Comment by SubOptimal** [comment]
@garfi303 Which text fields do you mean? The textarea has a dynamic size.
![grafik](https://user-images.githubusercontent.com/653288/81645344-b89ba700-9429-11ea-8673-8152e4a1b54b.png)

(using the current version from https://userstyles.org/styles/108591/github-wide)

**Comment by garfi303** [comment]
Not on my computer!


![image](https://user-images.githubusercontent.com/31320167/81686902-c26fdb00-9426-11ea-87d5-c5dd4abf686b.png)

I am using:
![image](https://user-images.githubusercontent.com/31320167/81687076-d87d9b80-9426-11ea-8466-41e749ecd654.png)

**Comment by SubOptimal** [comment]
@garfi303 Which version of github-wide are you using? And which FX extension do you use?
I use:
- github-wide from the above link
- FX extension Stylus (https://addons.mozilla.org/de/firefox/addon/styl-us/) version 1.5.11
- FX version 68.7.0esr

**Comment by garfi303** [comment]
@SubOptimal , thank you for your interest!
I am using:
* Stylus 1.5.10 (last updated March 25, 2020)
* github-wide version https://github.com/mdo/github-wide/commit/17c1ba0d2cb37cf85e4f1ad477e4ae1a73e58b13  (you do not seem to have embedded version numbers)

However, I have identified the problem! The problem does not appear on https://github.com/, but it does appear on my organization's copy of GitHub Enterprise!

We are using:

```
© 2020 GitHub, Inc.
GitHub Enterprise Server 2.18.10
```

**Comment by SubOptimal** [comment]
Open the Stylus "Manage" menu and add the URL of your corporate GitHub instance
![image](https://user-images.githubusercontent.com/653288/81842987-3efcd980-954d-11ea-8d6a-6ebf0bda0cf7.png)

**Comment by garfi303** [comment]
I did that (I actually set up its own set of rules). It is being applied throughout the site--- for example, it's on the issue list. It's just not on the individual boxes when looking at a specific issue.
