### ISSUE TITLE
GitHub Enterprise?

### ISSUE THREAD

**Issue by timcanham** [mdo/github-wide#75]
I tried installing this for our GitHub enterprise and it doesn't seem to affect the width. Any ideas?

**Comment by clrosier** [comment]
+1.
Also wondering about this, I've tried it for public GitHub and it's great.  Would also appreciate GHE support!

**Comment by cfoellmann** [comment]
is it applied to the webpage? Did you set the url for your style?

**Comment by twogood** [comment]
![image](https://user-images.githubusercontent.com/189982/98098192-4d89d500-1e8e-11eb-9377-9c3b5f738f48.png)

Seems to work fine for GHE if I add the URL to the style!

**Comment by mdo** [comment]
Closing out since this seems like it's not an issue.
